FinalTask(1)/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FinalTask_1_.Models
{
   /* public class UserViewModel
    {
        public string Id { get; set; }

        public string name { get; set; }//user name & surname

        public string nick { get; set; }//nick ==login

        public string password { get; set; }

        // public bool Status { get; set; } добавить в модель на уровне логики и представления 

        public ICollection<UserViewModel> Friends { get; set; }
       
  
       [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Некорректный адрес")]

        public string email { get; set; }
        public DateTime date { get; set; }

       
    }*/
}

FinalTask(1)/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business.Interfaces;
using Business.Models;
using Business.Services;

namespace FinalTask_1_.Controllers
{ 
    public class UserController : Controller
    {
      
        
        IUserService service;
        public UserController(IUserService now)
        {
           service = now;

        }


       
        [HttpGet]
        public ActionResult Update(string id1)
        {
            if (id1 == null)
            {
                return HttpNotFound();
            }
            var alluser = service.GetAllUsers().ToList(); 
            
            var user = alluser.Find(x => x.Id==id1);
            if (user != null)
            {
                return View(user);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult Update(UserModel user)
        {
            service.onlyUpdate(user);
            return RedirectToAction("Update");
        }
        /// <summary>
        /// searcher
        /// </summary>
        /// <param name="id1"></param>
        /// <returns></returns>
        public ActionResult FindFriend(string id1)
        {
            var alluser = service.GetAllUsers().ToList();
            ViewBag.users = alluser;
            ViewBag.ouruser = id1;
            return View();

        }
        /// <summary>
        /// searcher result
        /// </summary>
        /// <param name="model"></param>
        /// <param name="id1"></param>
        /// <returns></returns>
        public ActionResult FriendsResult(UserModel model,string id1)
        {
            if (service.FindUser(model).Count != 0)
            {
                ViewBag.result = service.FindUser(model);
                ViewBag.ouruser = id1;
                return View();
            }

          
       
            ViewBag.result1 = "Ничего не найдено";

            ViewBag.ouruser = id1;
            return View();

        }
        public ActionResult AddFriend(string id1, string id2) //id1 хозяин  id2 друг
        {
            service.AddFriend(id1, id2);
           
            
            return View();
        }
    }
}

FinalTask(1)/Views/User/AddFriend.cshtml
<p></p>
<p></p>


<p>Друг добавлен</p>

FinalTask(1)/Views/User/FindFriend.cshtml
@model  Business.Models.UserModel
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
@Scripts.Render("~/Scripts/chat.js")
<p></p>
<p></p>
<p></p>
<p></p>

@using (Ajax.BeginForm("FriendsResult", new { id1 = ViewBag.ouruser }, new AjaxOptions { UpdateTargetId = "results" }))

{

    @Html.HiddenFor(m => m.Id)
    <p>
        @Html.LabelFor(m => m.nick, "Имя")
        <br />
        @Html.EditorFor(m => m.nick)
        @Html.ValidationMessageFor(m=>m.nick)
    </p>

    <p>
        @Html.LabelFor(m => m.mobile, "Телефон")
        <br />
        @Html.EditorFor(m => m.mobile)
        @Html.ValidationMessageFor(m => m.mobile)
    </p>
    <p>
        @Html.LabelFor(m => m.email, "Почта")
        <br />
        @Html.EditorFor(m => m.email)
        @Html.ValidationMessageFor(m => m.email)
    </p>
    
    <p><input type="submit" value="Поиск" /></p>

}




    <div id="results">


    </div>
   

FinalTask(1)/Views/User/FriendsResult.cshtml
@foreach (var i in ViewBag.result)
{


    <a href="/User/AddFriend/@ViewBag.ouruser/@i.Id"> @i.nick </a>

}
@ViewBag.result1

FinalTask(1)/Views/User/Update.cshtml
@{
    ViewBag.Title = "Редактировать";

}
@model Business.Models.UserModel
<p></p>
<p></p>
<p></p>
@using (Html.BeginForm("Update", "User", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.Id)

       
        <p>
            @Html.LabelFor(m => m.mobile, "Телефон")
            <br />
            @Html.EditorFor(m => m.mobile)
            @Html.ValidationMessageFor(model => model.mobile)
        </p>
        <p>
            @Html.LabelFor(m => m.email, "Почта")
            <br />
            @Html.EditorFor(m => m.email)
            @Html.ValidationMessageFor(model => model.email)
        </p>
        
        
        <p><input type="submit" value="Отправить" /></p>

    </fieldset>
}
@Scripts.Render("~/scripts/jquery-3.4.1.js")
@Scripts.Render("~/scripts/jquery.validate.js")
@Scripts.Render("~/scripts/jquery.validate.unobtrusive.js")